name: PowerShell Automation - Track Crypto

on:
  push:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run the scripts
        shell: pwsh
        run: |
          Import-Module ./Modules/ImportExcel.psd1 -Force
          Import-Module ./CryptoCoins.psm1 -Force

          ./GetCoinPrice.ps1
          ./CreateChartOfPriceOverTime.ps1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Check in results
          commit_user_name: "PowerShell Automation"
